// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyquzgmnlecwnlcqcydr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5cXV6Z21ubGVjd25sY3FjeWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODg5NTMsImV4cCI6MjA2OTY2NDk1M30.9mAGvjNR5xL72RXpWKqqD4_Vs8dwwEHpEBJ42DEJJ_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});